name: superduper
description: An alternative app for Super bikes
publish_to: 'none'
version: 0.0.21+21

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  flutter_foreground_task: ^4.0.0
  flutter_markdown: ^0.6.13
  flutter_reactive_ble: ^5.0.3
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  json_annotation: ^4.7.0
  permission_handler: ^10.2.0
  riverpod_annotation: ^1.0.6
  unique_name_generator: ^1.0.0
  url_launcher: ^6.1.8
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  build_runner:
  riverpod_generator: ^1.0.6
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/superduper-nobg.png


flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#DBECF0"
  adaptive_icon_foreground: "assets/superduper_android.png"
  ios: true
  image_path: "assets/superduper_android.png"
  image_path_ios: "assets/superduper.png"
  remove_alpha_ios: true