name: superduper
description: An app for super bikes
publish_to: "none"
version: 0.6.6+43

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_info_plus: ^10.0.0
  flutter_blue_plus: ^1.32.7
  flutter_foreground_task: ^6.0.0
  flutter_form_builder: ^9.0.0
  flutter_markdown: ^0.7.0
  flutter_riverpod: ^2.1.1
  form_builder_validators: ^10.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.0.0
  riverpod_annotation: ^2.0.0
  unique_name_generator: ^1.0.0
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^4.0.0
  freezed: ^2.5.0
  json_serializable: ^6.5.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/superduper-nobg.png

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#DBECF0"
  adaptive_icon_foreground: "assets/superduper_android.png"
  ios: true
  image_path: "assets/superduper_android.png"
  image_path_ios: "assets/superduper.png"
  remove_alpha_ios: true

